In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
#Let's deal with series:---
# series = A Pandas 1-Dimensional labeled array that  can hold any data type,think of it like a single
# column in a spreadsheet
import pandas as pd
data = [100,102,104] #or data = ["a","b","c"] this dtype: object

series = pd.Series(data)  # Now, this Series(), is a constructor with arguments
print(series)

0    100
1    102
2    104
dtype: int64

In [3]:
# WE can customize the index 
data = [100,102,104] 

series = pd.Series(data,index=["a","b","c"])  
print(series)

a    100
b    102
c    104
dtype: int64

In [6]:
# IF u want to access a value directly in series , u can do it with .loc
data = [100,102,104] 

series = pd.Series(data,index=["a","b","c"])  
print(series.loc["a"])   # i,e. return the value where the label is a

100

In [7]:
# U can also locate a value i.e, u can change a value like:---
data = [100,102,104] 

series = pd.Series(data,index=["a","b","c"])  
series.loc["a"]=200
print(series)

a    200
b    102
c    104
dtype: int64

In [9]:
# with .iloc , but .iloc only deals with int index like the original one 0,1,....
data = [100,102,104] 

series = pd.Series(data,index=["a","b","c"])  
print(series.iloc[0])

100

In [10]:
data = [100,102,104,205,250] 

series = pd.Series(data,index=["a","b","c","d","e"])  
print(series[series>200])

d    205
e    250
dtype: int64

In [13]:
#NOW will use dict, so i like pizzas,
import pandas as pd
calories = {"Day1":1750 ,"Day2":2200,"Day3":1700}
series=pd.Series(calories)  #since we are using dic , so we do not need to create a separate index=""
print(series)
print(series.loc["Day1"])

Day1    1750
Day2    2200
Day3    1700
dtype: int64
1750

In [15]:
# BUT TODAY I cheated and had a cookies so , now i need to update the series 
calories = {"Day1":1750 ,"Day2":2100,"Day3":1700}
series=pd.Series(calories)

series.loc["Day3"] +=500
print(series)

Day1    1750
Day2    2100
Day3    2200
dtype: int64

In [16]:
calories = {"Day1":1750 ,"Day2":2200,"Day3":1700}
series=pd.Series(calories) 
print(series[series>=2000])

Day2    2200
dtype: int64

DATA FRAME

In [17]:
# DATAFRAME = A tabular data structure with rows& columns(2 DIMENSIONAL)
import pandas as pd

data= {
    "Name": ["mia","rose", "jack"],
    "Age": [20, 30, 50]
}
# Now we will convert this dic to a dataframe
df = pd.DataFrame(data) #Now this DataFrame is a constructor 
print(df)   # now the o/p is a tabular one

   Name  Age
0   mia   20
1  rose   30
2  jack   50

In [22]:
data= {
    "Name": ["mia","rose", "jack"],
    "Age": [20, 30, 50]
}
df = pd.DataFrame(data, index=["Emp1","Emp2","Emp3"]) 
print(df)
print(df.loc["Emp1"])  # loc means location by label

      Name  Age
Emp1   mia   20
Emp2  rose   30
Emp3  jack   50
Name    mia
Age      20
Name: Emp1, dtype: object

In [28]:
data= {
    "Name": ["mia","rose", "jack"],
    "Age": [20, 30, 50]
}
df = pd.DataFrame(data, index=["Emp1","Emp2","Emp3"]) 

# ADD A NEW COLUMN
df["Job"]=["Dancer","N/A","CRICKETER"]

#ADD a new ROW
new_row = pd.DataFrame([{"Name":"Sandy","Age":27,"Job":"actress"}],index=["Emp4"])
#Now we need to concantinate this to the original one
df=pd.concat([df,new_row])
print(df)

       Name  Age        Job
Emp1    mia   20     Dancer
Emp2   rose   30        N/A
Emp3   jack   50  CRICKETER
Emp4  Sandy   27    actress

Load Real Dataset (IMPORTANT)

In [37]:
df = pd.read_csv("/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv")
df.head()  # df.head() is used to preview the first few rows of your dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [38]:
df = pd.read_csv("/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv")
df.info()  #It gives a summary of your dataset structure

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [40]:
df = pd.read_csv("/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv")
df.describe()   # It gives statistical summary of your numeric columns

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200